const CLIENT='48467ac6ee784c28af878e8d9223f3ad';
const REDIRECT='https://fabeec-dev.github.io/Ride-Web/';
const SCOPES='user-read-playback-state user-read-currently-playing user-modify-playback-state user-read-recently-played user-top-read';
const K={rides:'ride.pwa.rides.v1',spotify:'ride.pwa.spotify.v1',learn:'ride.pwa.learning.v1'};
const $=id=>document.getElementById(id),all=q=>[...document.querySelectorAll(q)];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let map,line,marker,watch=null,ride=null,timer=null,playback=null,planDuration=60,planMood='mix';
function icon(id){return `<svg><use href="#${id}"/></svg>`}function toast(s){$('toast').textContent=s;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),2500)}
function go(id){all('.screen').forEach(x=>x.classList.toggle('active',x.id===id));all('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));scrollTo({top:0,behavior:'smooth'});if(id==='ride')setTimeout(()=>map?.invalidateSize(),80)}
function distance(a,b){const r=x=>x*Math.PI/180,R=6371,d1=r(b.lat-a.lat),d2=r(b.lng-a.lng),q=Math.sin(d1/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(d2/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function clock(s){s=Math.max(0,Math.floor(s));const h=Math.floor(s/3600),m=Math.floor(s%3600/60),z=s%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(z).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(z).padStart(2,'0')}`}
function initMap(){if(!window.L){$('map').innerHTML='<div class="empty">Carte indisponible.</div>';return}map=L.map('map',{zoomControl:false,attributionControl:false}).setView([46.2044,6.1432],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(map);line=L.polyline([],{color:'#8b6cff',weight:6,opacity:.95}).addTo(map)}
function renderRide(){if(!ride){$('rideTime').textContent='00:00';$('rideDistance').textContent='0,00';$('rideSpeed').textContent='0';return}$('rideTime').textContent=clock((Date.now()-ride.startedAt)/1000);$('rideDistance').textContent=ride.distanceKm.toFixed(2).replace('.',',');$('rideSpeed').textContent=Math.round(ride.points.at(-1)?.speedKmh||0)}
function onPosition(p){if(!ride)return;const c=p.coords,n={lat:c.latitude,lng:c.longitude,t:p.timestamp,accuracy:Math.round(c.accuracy),speedKmh:Math.max(0,(c.speed||0)*3.6)},old=ride.points.at(-1);if(old){const d=distance(old,n);if(d<.35)ride.distanceKm+=d}ride.maxSpeedKmh=Math.max(ride.maxSpeedKmh,n.speedKmh);ride.points.push(n);$('gpsChip').textContent=c.accuracy<=30?'GPS précis':`GPS ±${Math.round(c.accuracy)} m`;line?.addLatLng([n.lat,n.lng]);if(map){if(!marker){marker=L.circleMarker([n.lat,n.lng],{radius:9,color:'#fff',weight:3,fillColor:'#8b6cff',fillOpacity:1}).addTo(map);map.setView([n.lat,n.lng],16)}else marker.setLatLng([n.lat,n.lng])}renderRide()}
function beginRide(){if(ride){go('ride');return toast('Une balade est déjà en cours.')}if(!navigator.geolocation)return toast('GPS indisponible.');ride={id:crypto.randomUUID?.()||String(Date.now()),startedAt:Date.now(),points:[],distanceKm:0,maxSpeedKmh:0,plan:{duration:planDuration,mood:planMood,returnToStart:$('returnToggle').checked}};$('rideTitle').textContent='Balade en cours';$('gpsChip').textContent='Localisation…';$('startRideBtn').classList.add('hidden');$('endRideBtn').classList.remove('hidden');$('ridePlayer').classList.toggle('hidden',!playback?.item);go('ride');watch=navigator.geolocation.watchPosition(onPosition,e=>toast(e.code===1?'Autorise la localisation dans Réglages.':'Signal GPS indisponible.'),{enableHighAccuracy:true,maximumAge:1000,timeout:15000});timer=setInterval(renderRide,1000);toast('Balade démarrée')}
function endRide(){if(!ride)return;if(watch!==null)navigator.geolocation.clearWatch(watch);clearInterval(timer);ride.endedAt=Date.now();const rides=read(K.rides,[]);rides.unshift(ride);write(K.rides,rides.slice(0,100));ride=null;watch=null;line?.setLatLngs([]);if(marker){map.removeLayer(marker);marker=null}$('rideTitle').textContent='Prêt à partir';$('gpsChip').textContent='GPS en attente';$('startRideBtn').classList.remove('hidden');$('endRideBtn').classList.add('hidden');$('ridePlayer').classList.add('hidden');renderRide();renderHistory();renderToday();toast('Balade enregistrée')}
function renderHistory(){const rides=read(K.rides,[]),list=$('historyList');$('historyQuickStatus').textContent=rides.length?`${rides.length} balade${rides.length>1?'s':''}`:'Aucune balade';if(!rides.length){list.innerHTML='<div class="empty"><div class="empty-art"></div><h3>La route commence ici</h3><p>Ta première balade apparaîtra ici avec sa durée, sa distance et sa vitesse maximale.</p></div>';return}list.innerHTML=rides.map(r=>{const d=new Date(r.startedAt),min=Math.max(1,Math.round(((r.endedAt||r.startedAt)-r.startedAt)/60000));return `<article class="history-card"><div class="route-thumb"></div><div><h3>${new Intl.DateTimeFormat('fr-CH',{weekday:'long',day:'numeric',month:'short'}).format(d)}</h3><p>${new Intl.DateTimeFormat('fr-CH',{hour:'2-digit',minute:'2-digit'}).format(d)} · ${min} min · ${r.plan?.mood||'libre'}</p></div><span><b>${Number(r.distanceKm||0).toFixed(1)} km</b><small>max ${Math.round(r.maxSpeedKmh||0)} km/h</small></span></article>`}).join('')}
function renderToday(){const n=new Date(),rs=read(K.rides,[]).filter(r=>new Date(r.startedAt).toDateString()===n.toDateString());$('todayDistance').textContent=rs.reduce((s,r)=>s+Number(r.distanceKm||0),0).toFixed(1).replace('.',',');$('todayMinutes').textContent=rs.reduce((s,r)=>s+Math.round(((r.endedAt||r.startedAt)-r.startedAt)/60000),0);$('todayRides').textContent=rs.length}
const b64=b=>btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const sess=()=>read(K.spotify,null),setSess=s=>s?write(K.spotify,s):localStorage.removeItem(K.spotify);
async function login(){const v=b64(crypto.getRandomValues(new Uint8Array(64))),state=b64(crypto.getRandomValues(new Uint8Array(24))),challenge=b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))));localStorage.setItem('ride.spotify.verifier',v);localStorage.setItem('ride.spotify.state',state);location.href='https://accounts.spotify.com/authorize?'+new URLSearchParams({client_id:CLIENT,response_type:'code',redirect_uri:REDIRECT,scope:SCOPES,code_challenge_method:'S256',code_challenge:challenge,state})}
async function callback(){const q=new URLSearchParams(location.search),code=q.get('code');if(!code)return;const v=localStorage.getItem('ride.spotify.verifier');if(!v||q.get('state')!==localStorage.getItem('ride.spotify.state'))return toast('Connexion Spotify invalide.');try{const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:CLIENT,grant_type:'authorization_code',code,redirect_uri:REDIRECT,code_verifier:v})});if(!r.ok)throw 0;const t=await r.json();setSess({accessToken:t.access_token,refreshToken:t.refresh_token,expiresAt:Date.now()+(t.expires_in-45)*1000});history.replaceState({},'',REDIRECT);toast('Spotify connecté')}catch{toast('Connexion Spotify impossible.')}}
async function refresh(s){const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:CLIENT,grant_type:'refresh_token',refresh_token:s.refreshToken})});if(!r.ok){setSess(null);return null}const t=await r.json(),n={accessToken:t.access_token,refreshToken:t.refresh_token||s.refreshToken,expiresAt:Date.now()+(t.expires_in-45)*1000};setSess(n);return n}async function token(){let s=sess();if(s&&Date.now()>=s.expiresAt)s=await refresh(s);return s?.accessToken}async function api(path,opt={},retry=true){const t=await token();if(!t)throw Error('not_connected');const r=await fetch('https://api.spotify.com/v1'+path,{...opt,headers:{Authorization:`Bearer ${t}`,...opt.headers}});if(r.status===401&&retry&&await refresh(sess()))return api(path,opt,false);if(r.status===204)return null;if(!r.ok){const e=Error();e.status=r.status;throw e}return r.json()}
function cover(el,url){el.style.backgroundImage=url?`url("${url}")`:'';el.innerHTML=url?'':icon('musicI');el.classList.toggle('placeholder',!url)}function learn(){return read(K.learn,{skips:0,observations:0,hours:{}})}function renderLearn(){const l=learn(),h=Object.entries(l.hours).sort((a,b)=>b[1]-a[1]);$('skipCount').textContent=l.skips;$('fullPlayCount').textContent=l.observations;$('favoritePeriod').textContent=h.length?`Vers ${h[0][0]} h`:'Pas encore assez de données'}function observe(d){if(!d?.item?.id||!d.is_playing||sessionStorage.getItem('ride.lastTrack')===d.item.id)return;sessionStorage.setItem('ride.lastTrack',d.item.id);const l=learn(),h=String(new Date().getHours());l.observations++;l.hours[h]=(l.hours[h]||0)+1;write(K.learn,l);renderLearn()}
function showPlayback(d){const i=d?.item,title=i?.name||'Aucun morceau',artist=i?.artists?.map(a=>a.name).join(', ')||(sess()?'Lance Spotify sur un appareil':'Connecte ton compte Spotify'),img=i?.album?.images?.[0]?.url;$('musicTrack').textContent=title;$('musicArtist').textContent=artist;$('homeTrack').textContent=i?.name||(sess()?'Spotify connecté':'Connecte Spotify');$('homeArtist').textContent=i?artist:'Ride suivra ta musique ici';$('spotifyDevice').textContent=d?.device?.name?`Sur ${d.device.name}`:'Aucun appareil détecté';$('playPauseBtn').innerHTML=icon(d?.is_playing?'pauseI':'playI');$('trackProgress').style.width=i?`${Math.min(100,d.progress_ms/i.duration_ms*100)}%`:'0';$('rideTrack').textContent=title;$('rideArtist').textContent=artist;cover($('musicCover'),img);cover($('homeCover'),img);cover($('rideCover'),img)}
function renderSpotify(){const on=!!sess();$('spotifyConnectBtn').textContent=on?'Déconnecter':'Connecter';$('spotifyQuickStatus').textContent=on?'Connecté':'Non connecté';$('heroSpotifyStatus').textContent=on?'Spotify connecté':'Spotify hors ligne'}async function refreshPlayback(){renderSpotify();if(!sess())return showPlayback(null);try{playback=await api('/me/player');showPlayback(playback);observe(playback)}catch{}}
async function control(a){try{if(!sess())return login();const method=a==='previous'?'/me/player/previous':a==='next'?'/me/player/next':a==='play'?'/me/player/play':'/me/player/pause';await api(method,{method:a==='play'||a==='pause'?'PUT':'POST'});if(a==='next'){const l=learn();l.skips++;write(K.learn,l);renderLearn()}setTimeout(refreshPlayback,500)}catch(e){toast(e.status===403?'Spotify Premium peut être requis.':e.status===404?'Lance Spotify sur un appareil.':'Commande Spotify indisponible.')}}
function modal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modalBackdrop').classList.remove('hidden')}function settings(){modal('Réglages',`<div class="sheet-row"><b>Spotify</b><p>${sess()?'Connecté':'Non connecté'} · OAuth PKCE, sans Client Secret.</p></div><div class="sheet-row"><b>GPS</b><p>Le suivi fonctionne tant que la PWA reste active. iOS ne garantit pas le GPS continu écran verrouillé.</p></div><div class="sheet-row"><b>Données locales</b><p>Trajets et apprentissage restent dans ce navigateur.</p></div><div class="sheet-row"><b>Apprentissage musical</b><p>Ride observe les morceaux et compte les skips effectués avec ses commandes.</p></div><div class="sheet-row"><b>Installation PWA</b><p>Safari → Partager → Sur l’écran d’accueil.</p></div><div class="sheet-row"><b>Confidentialité</b><p>Aucun Client Secret ni serveur Ride. Spotify reçoit uniquement les appels nécessaires.</p></div><div class="sheet-row"><b>À propos de Ride</b><p>Copilote personnel pour tes balades en scooter.</p></div><div class="sheet-row"><b>Technique</b><p class="tag">Redirect Spotify : ${REDIRECT}</p></div>`)}
function planText(){const d=planDuration<60?`${planDuration} min`:planDuration===60?'1 h':`${planDuration/60} h`,m=planMood==='energie'?'Énergie':planMood==='calme'?'Calme':'Mix';$('planSummary').textContent=`${d} · ${m}${$('returnToggle').checked?' · Retour au départ':''}`}
function bind(){all('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));$('startRideHero').onclick=$('startRideBtn').onclick=$('launchPlanBtn').onclick=beginRide;$('endRideBtn').onclick=endRide;$('centerMapBtn').onclick=()=>{const p=ride?.points.at(-1);p&&map?map.setView([p.lat,p.lng],16):toast('Pas encore de position GPS.')};$('spotifyConnectBtn').onclick=()=>sess()?(setSess(null),renderSpotify(),showPlayback(null),toast('Spotify déconnecté')):login();$('nextBtn').onclick=()=>control('next');$('prevBtn').onclick=()=>control('previous');$('playPauseBtn').onclick=()=>control(playback?.is_playing?'pause':'play');$('settingsBtn').onclick=settings;$('installHelpBtn').onclick=()=>modal('Installer Ride','<div class="sheet-row"><b>Sur iPhone</b><p>Ouvre Ride dans Safari, puis Partager → Sur l’écran d’accueil → Ajouter.</p></div>');$('modalClose').onclick=()=>$('modalBackdrop').classList.add('hidden');$('modalBackdrop').onclick=e=>{if(e.target===$('modalBackdrop'))$('modalBackdrop').classList.add('hidden')};$('clearHistoryBtn').onclick=()=>{if(confirm('Effacer toutes les balades ?')){localStorage.removeItem(K.rides);renderHistory();renderToday()}};all('#durationSegments button').forEach(b=>b.onclick=()=>{all('#durationSegments button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');planDuration=+b.dataset.duration;planText()});all('#moodSegments button').forEach(b=>b.onclick=()=>{all('#moodSegments button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');planMood=b.dataset.mood;planText()});$('returnToggle').onchange=planText;addEventListener('online',renderConnection);addEventListener('offline',renderConnection)}function renderConnection(){$('connectionText').textContent=navigator.onLine?'En ligne':'Hors ligne';$('connectionChip').classList.toggle('neutral',!navigator.onLine)}
async function init(){$('todayDate').textContent=new Intl.DateTimeFormat('fr-CH',{weekday:'short',day:'numeric',month:'short'}).format(new Date());initMap();bind();renderHistory();renderToday();renderLearn();renderSpotify();renderConnection();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});await callback();await refreshPlayback();setInterval(()=>document.visibilityState==='visible'&&sess()&&refreshPlayback(),8000)}init();
